# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.IntegerField(choices=[(0, 'Прогулянка із псом'), (1, 'Похід за продуктами'), (2, 'Миття вікон'), (3, 'Ремонт меблів'), (4, 'Супровід дитини у школу'), (5, 'Ремонт одягу'), (6, 'Миття машини'), (7, 'Послуги няні'), (8, 'Ремонт велосипеду'), (9, 'Догляд за домашньою твариною на певний час'), (10, 'Допомога з перевезенням речей'), (11, 'Фарбування паркану'), (12, 'Прибирання квартири'), (13, 'Миття посуду')]),
        ),
    ]
